apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:17.5-alpine
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: platform-secret
        volumeMounts:
        - name: db-volume
          mountPath: /var/opts/db
      volumes: 
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-pvc          


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    app: db
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce


---

apiVersion: v1 
kind: Service 
metadata:
  name: db-service
  labels:
    app: db
spec:
  selector:
    app: db
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP